image: node:20

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - npm install --only=dev
          - chmod +x node_modules/.bin/nodemon
          - npm start
    # Uncomment this for linting if needed
    # - step:
    #     name: Code linting
    #     script:
    #       - npm install eslint
    #       - npx eslint .
    #     caches:
    #       - node
